/*
DROP TABLE IF EXISTS order_infos;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS books;
 */

CREATE TABLE IF NOT EXISTS books (
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR(75) UNIQUE NOT NULL,
	price DECIMAL(6,2)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR(75) UNIQUE NOT NULL,
  "password" VARCHAR(75) NOT NULL,
  "role" INT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT REFERENCES users NOT NULL,
  total_cost DECIMAL(8,2) NOT NULL,
  status INT NOT NULL DEFAULT 0 
);

CREATE TABLE IF NOT EXISTS order_infos (
  id BIGSERIAL PRIMARY KEY,
  order_id BIGINT REFERENCES orders NOT NULL,
  book_id BIGINT REFERENCES books NOT NULL,
  book_quantity INT NOT NULL DEFAULT 1,
  book_price DECIMAL(6,2) NOT NULL,
  CONSTRAINT order_infos_pk UNIQUE (order_id, book_id)
);